import json
import logging

# Import LLM client used to communicate with the Groq AI model
from ai_engine.llm_client import ask_llm

# Import decision engine that selects CI/CD stages based on repo analysis
from ai_engine.pipeline_brain import decide_pipeline


# Configure logging format for tracking pipeline generation workflow
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


def clean_commands(commands: str) -> str:
    # Remove markdown formatting returned by the LLM to keep only executable shell commands
    commands = commands.replace("```bash", "")
    commands = commands.replace("```", "")
    return commands.strip()


def load_analysis() -> dict:
    # Load repository analysis results generated by repo_analyzer
    try:
        with open("analysis.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        logging.error("analysis.json not found. Run repo_analyzer first.")
        raise


def select_valid_stages(analysis: dict, stages: list) -> list:
    # Filter pipeline stages to ensure they match technologies detected in the repository

    valid_stages = []
    language = str(analysis.get("Language", "")).lower()

    for stage in stages:

        # Allow Python dependency stage only if Python is detected
        if stage == "install_dependencies" and "python" not in language:
            continue

        # Allow Maven build stage only if Java is detected
        if stage == "maven_build" and "java" not in language:
            continue

        # Allow Docker stages only if Docker usage is detected
        if stage in ["docker_build", "docker_push"] and not analysis.get("docker"):
            continue

        # Allow Kubernetes deployment only if Kubernetes manifests exist
        if stage == "kubernetes_deploy" and not analysis.get("kubernetes"):
            continue

        # Allow Terraform execution only if Terraform configuration exists
        if stage == "terraform_apply" and not analysis.get("terraform"):
            continue

        # Allow Ansible deployment only if Ansible configuration exists
        if stage == "ansible_deploy" and not analysis.get("ansible"):
            continue

        valid_stages.append(stage)

    # Remove duplicate stages while preserving order
    return list(dict.fromkeys(valid_stages))


def build_prompt(analysis: dict, stages: list) -> str:
    # Build the DevOps prompt that instructs the LLM to generate a CI/CD pipeline

    prompt = f"""
You are a Senior DevOps Engineer.

Repository analysis:
{json.dumps(analysis, indent=2)}

Pipeline stages selected:
{stages}

Generate a bash CI/CD pipeline.

Rules:
- Output ONLY executable bash commands
- No explanations or comments
- Commands must run in Linux CI environments
- Follow the stage order exactly
- NEVER execute commands for files that do not exist

Safety rules:
- If requirements.txt is missing, skip pip install
- If package.json is missing, skip npm install
- If pom.xml is missing, skip maven build

Examples:

Python dependency install (safe version):
if [ -f requirements.txt ]; then
    pip install -r requirements.txt
fi

Node dependency install (safe version):
if [ -f package.json ]; then
    npm install
fi

Java build:
if [ -f pom.xml ]; then
    mvn clean package
fi

Docker build:
docker build -t ai-devops-app:latest .

Docker push:
docker push ai-devops-app:latest

Kubernetes deploy:
kubectl apply -f k8s/
"""

    return prompt


def write_pipeline(commands: str):
    # Write generated CI/CD commands into an executable bash script

    with open("generated_pipeline.sh", "w") as f:
        f.write("#!/bin/bash\n\n")
        f.write("set -e\n\n")
        f.write(commands + "\n")

    logging.info("Pipeline script written to generated_pipeline.sh")


def generate_pipeline():
    # Main workflow that analyzes the repository and generates AI-driven CI/CD pipeline

    logging.info("Loading repository analysis")

    analysis = load_analysis()

    logging.info("Deciding pipeline stages")

    stages = decide_pipeline(analysis)

    # Filter stages based on detected technologies
    stages = select_valid_stages(analysis, stages)

    if not stages:
        logging.warning("No pipeline stages detected. Exiting.")
        return

    logging.info(f"Stages selected: {stages}")

    logging.info("Building AI prompt")

    prompt = build_prompt(analysis, stages)

    logging.info("Requesting pipeline from LLM")

    response = ask_llm(prompt)

    commands = clean_commands(response)

    write_pipeline(commands)

    logging.info("Pipeline generation completed")


if __name__ == "__main__":

    # Entry point for executing the AI pipeline generator
    logging.info("Starting AI pipeline generation")

    generate_pipeline()