import json
import logging

# Import LLM client used to communicate with the Groq AI model
from ai_engine.llm_client import ask_llm

# Import decision engine that selects CI/CD stages based on repo analysis
from ai_engine.pipeline_brain import decide_pipeline


# Configure logging format for tracking pipeline generation workflow
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)


def clean_commands(commands: str) -> str:
    # Remove markdown formatting returned by the LLM to keep only executable shell commands
    commands = commands.replace("```bash", "")
    commands = commands.replace("```", "")
    return commands.strip()


def load_analysis() -> dict:
    # Load repository analysis results generated by the repo_analyzer module
    try:
        with open("analysis.json", "r") as f:
            return json.load(f)
    except FileNotFoundError:
        logging.error("analysis.json not found. Run repo_analyzer first.")
        raise


def select_valid_stages(analysis: dict, stages: list) -> list:
    # Filter pipeline stages to ensure they match detected technologies in the repository

    valid_stages = []

    language = analysis.get("Language", "").lower()

    for stage in stages:

        # Allow Python dependency installation only if repository contains Python
        if stage == "install_dependencies" and "python" not in language:
            continue

        # Allow Maven build stage only if Java is detected
        if stage == "maven_build" and "java" not in language:
            continue

        # Allow Docker stages only if docker configuration exists in the repository
        if stage in ["docker_build", "docker_push"] and not analysis.get("docker"):
            continue

        # Allow Kubernetes deployment only if Kubernetes manifests are detected
        if stage == "kubernetes_deploy" and not analysis.get("kubernetes"):
            continue

        # Allow Terraform execution only if Terraform infrastructure exists
        if stage == "terraform_apply" and not analysis.get("terraform"):
            continue

        # Allow Ansible deployment only if Ansible configuration exists
        if stage == "ansible_deploy" and not analysis.get("ansible"):
            continue

        valid_stages.append(stage)

    # Remove duplicate stages while preserving original order
    return list(dict.fromkeys(valid_stages))


def build_prompt(analysis: dict, stages: list) -> str:
    # Construct the DevOps prompt sent to the LLM for generating pipeline commands

    prompt = f"""
You are a Senior DevOps Engineer.

Repository analysis:
{json.dumps(analysis, indent=2)}

Pipeline stages decided by the AI engine:
{stages}

Generate a bash CI/CD pipeline.

Rules:
- Output ONLY executable bash commands
- No explanations
- Commands must work in Linux CI environments
- Follow the order of stages

Stage guidelines:

If Python project:
install_dependencies → pip install -r requirements.txt
run_tests → pytest
security_scan → bandit -r .

If Java project:
install_dependencies → mvn clean install
run_tests → mvn test
security_scan → mvn dependency-check:check

If Node project:
install_dependencies → npm install
run_tests → npm test
security_scan → npm audit

docker_build → docker build -t ai-devops-app:latest .
docker_push → docker push ai-devops-app:latest
kubernetes_deploy → kubectl apply -f k8s/
terraform_apply → terraform init && terraform apply -auto-approve
ansible_deploy → ansible-playbook deploy.yml
"""

    return prompt


def write_pipeline(commands: str):
    # Write generated CI/CD commands into an executable bash script

    with open("generated_pipeline.sh", "w") as f:
        f.write("#!/bin/bash\n\n")
        f.write("set -e\n\n")
        f.write(commands + "\n")

    logging.info("Pipeline script written to generated_pipeline.sh")


def generate_pipeline():
    # Main workflow that analyzes the repo and generates an AI-powered CI/CD pipeline

    logging.info("Loading repository analysis")

    analysis = load_analysis()

    logging.info("Deciding pipeline stages")

    stages = decide_pipeline(analysis)

    # Filter stages based on detected repository technologies
    stages = select_valid_stages(analysis, stages)

    if not stages:
        logging.warning("No pipeline stages detected. Exiting.")
        return

    logging.info(f"Stages selected: {stages}")

    logging.info("Building AI prompt")

    prompt = build_prompt(analysis, stages)

    logging.info("Requesting pipeline from LLM")

    response = ask_llm(prompt)

    commands = clean_commands(response)

    write_pipeline(commands)

    logging.info("Pipeline generation completed")


if __name__ == "__main__":

    # Entry point for executing the AI pipeline generation module
    logging.info("Starting AI pipeline generation")

    generate_pipeline()