pipeline {

    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/dkasha14/ai-driven-jenkins-shared-library.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Analyze Repository') {
            steps {
                sh 'python -m ai_engine.repo_analyzer'
            }
        }

        stage('Decide Pipeline Stages') {
            steps {
                sh 'python -m ai_engine.pipeline_brain'
            }
        }

        stage('Generate CI/CD Pipeline') {
            steps {
                sh 'python -m ai_engine.pipeline_generator'
            }
        }

        stage('Execute Generated Pipeline') {
            steps {
                sh '''
                chmod +x generated_pipeline.sh
                ./generated_pipeline.sh
                '''
            }
        }

    }

}